### ISSUE TITLE
Problem regarding several properties in one file

### ISSUE THREAD

**Issue by BlueJCash** [fluentverification/stamina-storm#40]
Stamina produces the following error when a user is attempting to check several properties at once.

ERROR (Model.cpp:58): Invalid item count (0) of state labeling (states: 1).
[ERROR]: STAMINA encountered the following (possibly recoverable) error:
        STAMINA encountered the following error (possibly in the interface with STORM) in the function StaminaModelBuilder::build():
        IllegalArgumentException: Invalid item count (0) of state labeling (states: 1).
Segmentation fault

Contents of property file being inserted:
P=? [ true U[0,60000] ((!valid) & (!ack) & (!done) & (!rdy)) ]; //0000//
P=? [ true U[0,60000] ((!valid) & (!ack) & (!done) & (rdy)) ]; //0001//
P=? [ true U[0,60000] ((!valid) & (!ack) & (done) & (!rdy)) ]; //0010//
P=? [ true U[0,60000] ((!valid) & (!ack) & (done) & (rdy)) ]; //0011//
P=? [ true U[0,60000] ((!valid) & (ack) & (!done) & (!rdy)) ]; //0100//
P=? [ true U[0,60000] ((!valid) & (ack) & (!done) & (rdy)) ]; //0101//
P=? [ true U[0,60000] ((!valid) & (ack) & (done) & (!rdy)) ]; //0110//
P=? [ true U[0,60000] ((!valid) & (ack) & (done) & (rdy)) ]; //0111//
P=? [ true U[0,60000] ((valid) & (!ack) & (!done) & (!rdy)) ]; //1000//
P=? [ true U[0,60000] ((valid) & (!ack) & (!done) & (rdy)) ]; //1001//
P=? [ true U[0,60000] ((valid) & (!ack) & (done) & (!rdy)) ]; //1010//
P=? [ true U[0,60000] ((valid) & (!ack) & (done) & (rdy)) ]; //1011//
P=? [ true U[0,60000] ((valid) & (ack) & (!done) & (!rdy)) ]; //1100//
P=? [ true U[0,60000] ((valid) & (ack) & (!done) & (rdy)) ]; //1101//
P=? [ true U[0,60000] ((valid) & (ack) & (done) & (!rdy)) ]; //1110//
P=? [ true U[0,60000] ((valid) & (ack) & (done) & (rdy)) ]; //1111//

**Comment by ifndefJOSH** [comment]
@BlueJCash could you send me the model and properties file you used on slack? I would like to test on your model file specifically

**Comment by BlueJCash** [comment]
Ok, I’ll try to send them in a bit. I have not used slack in a while so it may take some time.

Tom Prouty

On Jan 12, 2023, at 3:26 PM, Josh Jeppson ***@***.***> wrote:

﻿

@BlueJCash<https://github.com/BlueJCash> could you send me the model and properties file you used on slack? I would like to test on your model file specifically

**Comment by ifndefJOSH** [comment]
Is fixed by #48
